### PR TITLE
feat: add DocSearch as recommended by vuepress

### PR DESCRIPTION
**Pull request by s-pace**
👋 team,

I am working on DocSearch. [We have an integration for Vuepress](https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search). We thought it is a shame you can not also used this search that you can [find on vuejs for example](https://vuejs.org/).

This PR will add DocSearch to the documentation website. It will allow an user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.

Let me know if you need anything.

### CODE REVIEW

**Comment by datitisev** [comment]
Looks great. Thanks for the PR! 🙂

**Comment by datitisev** [comment]
Actually - looks like search results include the `docs` path in the search results, causing a chain of `/docs/docs` etc.

Is this because of an incorrect configuration in our part?

**Comment by franzliedke** [comment]
@s-pace @datitisev Do we have to do anything to update the search index when we deploy the latest version?

**Comment by s-pace** [comment]
You can wait for 24H or ping me. I have triggered the crawl manually. We are working on making it on demand

**Comment by franzliedke** [comment]
Oh, great. 24 hours is perfectly fine for us, I would think.

Does the crawling happen on the Git repo, or on the version that is deployed on our site? (Right now, pushes to the master branch in flarum/docs do not trigger site rollouts.)

**Comment by s-pace** [comment]
It only fetch data from the live website yes

**Pull request merged**
