### PR TITLE
Add Prettier formatting for docs

### PR DESCRIPTION
**Pull request by davwheat**
As discussed in Discord: https://canary.discord.com/channels/360670804914208769/446433294607974430/827556677398036541

### CODE REVIEW

**Comment by askvortsov1** [comment]
Let's wait to merge this until we get #178 in

**Comment by davwheat** [comment]
@askvortsov1 What's preventing that being merged at the moment?

**Comment by askvortsov1** [comment]
> @askvortsov1 What's preventing that being merged at the moment, out of curiousity?

I keep forgetting to leave a review

**Comment by datitisev** [comment]
I don't like how the PHP codeblocks are being formatted... 
image

**Comment by askvortsov1** [comment]
Agreed, can we keep the 4 spaces?

**Comment by askvortsov1** [comment]
@davwheat After #374 and #334 are merged (or closed), could we rebase this and adjust for Docusaurus? We'll also only want to apply prettier to the English docs, since translations will be managed via crowdin.

**Comment by askvortsov1** [comment]
> > @davwheat After #374 and #334 are merged (or closed), could we rebase this and adjust for Docusaurus? We'll also only want to apply prettier to the English docs, since translations will be managed via crowdin.
> 
> #374 closed, can't wait for the Docusaurus 😃

We're already on Docusaurus (docs.flarum.org), which is why there were a bunch of merge conflicts in that PR. It should make translations easier to maintain (crowdin provides a GUI, plus you dont need sidebars for each language, and the file organization is a lot neater, and a few other things).

**Pull request closed without merging**
