### PR TITLE
Update install.md

### PR DESCRIPTION
**Pull request by lvzx123**

### CODE REVIEW

**Comment by Littlegolden** [comment]
没必要吧

**Comment by luceos** [comment]
@lvzx123 pull requests without a description are very hard to review. Especially because it's an unknown language to most maintainers.

@Littlegolden care to explain?

**Comment by Littlegolden** [comment]
@luceos This PR changes the "path to flarum" in Chinese to English.

**Comment by luceos** [comment]
Thanks for clarifying 👍

**Pull request closed without merging**
