### PR TITLE
Fixes Caddy Configuration

### PR DESCRIPTION
**Pull request by tankerkiller125**
Removed random comma that doesn't belong

### CODE REVIEW

**Comment by franzliedke** [comment]
Thanks a lot! :heart: Are you using Caddy?

**Comment by tankerkiller125** [comment]
Yes, I am using Caddy to host my forum and in fact all of my websites.

**Comment by franzliedke** [comment]
Cool, haven't come across too many people using it yet. Seems very slick!

**Comment by tankerkiller125** [comment]
The automatic LetsEncrypt implementation is why I originally started using it for personal sites, It's sense grown on me and some of the features are just too good to pass up on. Notably when on larger infrastructure the ability for it to get the certs and then automatically share it across every instance (Auto Scaling Anyone?) using redis has just made it the default tool in my toolbox, I only use Nginx and Apache when I absolutely have too and even then I usually proxy it through caddy.

**Pull request merged**
