### PR TITLE
Support Chinese Documentation

### PR DESCRIPTION
**Pull request by Littlegolden**
I haven't translated the /extend document yet as requested [before](https://github.com/flarum/docs/issues/87#issuecomment-619345895).

I found [the new PR]( #106 ) today and just realized the translation I almost forgot about.

As you guys discussed in that PR, I have categorized the configuration files, and I can expect that many different language translations will be PRed in the future, so I think the categorization will be very helpful to the developers involved.

Also, to prevent private information from being leaked, I unified the way the secret id used by the plugin is loaded, in such a way that the secret information (/config/secret.js) will always be stored in the local machine of the developer who eventually generates the static web page. 

BTW, I added a new plugin (@vuepress/plugin-container) to display the Flarum default directory structure (custom style) in  `/zh/install.html#url-rewrite`. The effect is like this (There's actually no change to the en files):
image

Oh, and the Contributor License Agreement, I have referred to the English version of various website agreement terms and the corresponding Chinese version (Adobe/Google/ etc.), and I can confirm that there is no error.

Above, I hope you like it！

### CODE REVIEW

**Comment by datitisev** [comment]
❓ Perhaps we want to add a warning to the Chinese documentation that says it may be outdated?

--- 

This looks fine to me - apart from some things that I have fixed locally, including:

- revert secret.js (API key was provided to us, it's used in FOSS projects)
- fix issues with sidebar (`/extend/` must go before `/` in `en` sidebar)
- reorganize folder structure
    image

These things I have already fixed, see https://github.com/flarum/docs/commit/87c9ecae95c7b84847989f82308902efa9549b96.

If the rest of this PR looks fine, I'll close it and merge our `locales/zh` branch into master. The Chinese extending docs can be PR'd at another time.

**Comment by Littlegolden** [comment]
> Perhaps we want to add a warning to the Chinese documentation that says it may be outdated?
Yeah, we need this. I have added an obsolete reminder to the homepage. https://github.com/flarum/docs/pull/107/commits/93ce635c9d9ecf5d373879249cc315f3f46d0595

> If the rest of this PR looks fine, we can merge it and put in the changes above afterwards. The Chinese extending docs can be PR'd at another time.

Okey, nice.

**Comment by Littlegolden** [comment]
All done~

**Comment by luceos** [comment]
Thank you @Littlegolden 👍

**Pull request merged**
