### PR TITLE
Rename index.md's to README

### LINKED ISSUE #37: "Edit this page" link doesn't work for index pages
If you click "Edit this page" at https://flarum.org/docs/extend/ you will be taken to https://github.com/flarum/docs/edit/master/docs/extend/README.md instead of https://github.com/flarum/docs/edit/master/docs/extend/index.md

Same for https://flarum.org/docs/

### PR DESCRIPTION
**Pull request by OrdinaryJellyfish**
Fixes #37

### CODE REVIEW

**Comment by Uzume** [comment]
It would be nice to have "Mithril" link to something like:
- https://mithril.js.org/
- https://github.com/MithrilJS/mithril.js

**Comment by franzliedke** [comment]
@Uzume We do so in several places throughout the docs... can you clarify what you mean?

**Comment by Uzume** [comment]
Well this PR is about the index or README so I meant that with regard to the following text:

> The interface is powered by Mithril, a performant JavaScript framework with a tiny footprint

**Comment by franzliedke** [comment]
Done in 906dc12a1ecc2da197602c9bc9a43cc3cc2d2233.

**Comment by Uzume** [comment]
Thanks! Now I can see https://flarum.org/docs/ directly links to Mithril right where it is first mentioned

**Pull request merged**
