### PR TITLE
Updated instructions to fix permissions errors

### PR DESCRIPTION
**Pull request by nina-py**
Add-on to the PR that updates the error message during installation - flarum/core#2435. 

Fixes flarum/core#2327

### CODE REVIEW

**Review by askvortsov1 — CHANGES_REQUESTED** [review]
Users that need this documentation are likely to be unfamiliar with server administration, so I think it might be better to add a bit more explanation of what folder ownership and these commands mean (or add some links to sources that explain it well)

**Comment by nina-py** [comment]
@askvortsov1 , sure, I'll give it a go! Do you think it would be a good idea to mention that for some Linux distros you need to prefix these commands with `sudo` as well?

**Comment by askvortsov1** [comment]
> @askvortsov1 , sure, I'll give it a go! Do you think it would be a good idea to mention that for some Linux distros you need to prefix these commands with `sudo` as well?

Perhaps. A bit about Windows might be nice too. I do think that links for background info might be the way to go: that way we can keep our docs slim and focused on the actual flarum stuff (as we do in other parts of the docs).

**Comment by nina-py** [comment]
Agree re slim answers with links - there appears to be a canonical answer on SuperUser for Windows users that we could use: https://superuser.com/questions/106181/equivalent-of-chmod-to-change-file-permissions-in-windows. For Linux file permissions in general, I could link to this tutorial from the Linux Foundation: https://www.linux.com/training-tutorials/understanding-linux-file-permissions/.

**Comment by askvortsov1** [comment]
I also like https://www.thegeekdiary.com/understanding-basic-file-permissions-and-ownership-in-linux/. And the Linux foundation needs to work on their css :rofl:

**Review by askvortsov1 — APPROVED** [review]

**Review by tankerkiller125 — APPROVED** [review]

**Pull request merged**
