### PR TITLE
Added an alternative to install through composer

### PR DESCRIPTION
**Pull request by Sarveshmrao**
Added an alternative to install through composer: just run the below composer line in your computer and install the generated vendor for to your server through ftp.

### CODE REVIEW

**Comment by franzliedke** [comment]
@flarum/docs Do we want to support this?

I think this was discussed before - and IIRC, we did not want to, as there are no guarantees that the prerequisites checked to be present when executing `composer` will be present on the production system as well.

**Comment by askvortsov1** [comment]
I'm all fine with mentioning it as an option, but there should definitely be some very strongly worded disclaimers that it isn't an official installation method and that if the environments don't match, unexpected issues may occur.

**Comment by luceos** [comment]
I'm becoming increasingly less a fan of openly promoting alternate solutions, including pockethold. Can't we create this under a FAQ or separate "trouble installing" page?

**Comment by askvortsov1** [comment]
Agreed. IMO composer 2 took care of the last remaining reasons to use alternatives, and pocket hold isn't fully maintained. If we eventually add some kind of UI for composer we can revisit this, but until then I think we're fine.

**Comment by askvortsov1** [comment]
Superceded by #194

**Pull request closed without merging**
