### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by razonyang**

### CODE REVIEW

**Review by tankerkiller125 — APPROVED** [review]
Although I don't speak chinese I do think Bub is the incorrect spelling of Bug. Good catch

**Comment by franzliedke** [comment]
Were the emojis intentionally removedß

**Comment by askvortsov1** [comment]
I don't speak Chinese, and unfortunately can't really contribute to this discussion. @Littlegolden  how do you feel about these changes?

**Comment by razonyang** [comment]
@franzliedke That is my mistake, my Chromium doesn't show these emojis.

**Comment by Littlegolden** [comment]
@askvortsov1 Yes it's a typo, I wrote the bug as bub. lol

**Pull request merged**
