### PR TITLE
Fix chat links to point to discord-redirector

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @luceos 

I've noticed the chat links being broken. Here is a small fix for this. 

(Also automatically fixes trailing spaces)

Cheers!

### CODE REVIEW

**Comment by luceos** [comment]
Awesome, how could we have missed that. I guess merging makes sense, I will always set up a redirection for /chat to /discord 👍

**Review by luceos — APPROVED** [review]

**Comment by spekulatius** [comment]
Hey @luceos 

no worries - we all miss things! I've just started playing around with Flarum and noticed this in the docs.

Btw, is there something like the typical "awesome list" of extensions ?

Cheers,
Peter

**Comment by luceos** [comment]
@spekulatius Hi Peter,

Check https://extiverse.com 👍

**Comment by spekulatius** [comment]
Ah awesome, thanks @luceos !

**Review by askvortsov1 — APPROVED** [review]

**Pull request merged**
